name: clean_architecture
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  get_it: ^7.6.7
  intl: ^0.19.0
  floor: ^1.4.2
  retrofit: ^4.1.0
  flutter_hooks: ^0.20.5
  cached_network_image: ^3.3.1
  dio: ^5.4.1
  sqflite: ^2.3.2
  ionicons: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: ^8.1.0
  floor_generator: ^1.4.2
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
